services:
  - type: web
    name: gestion-mesas-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: ConnectionStrings__Restaurant
        fromDatabase:
          name: gestion-mesas-db
          property: connectionString

databases:
  - name: gestion-mesas-db
    plan: free